### ISSUE TITLE
More of a question really...

### ISSUE THREAD

**Issue by callen5914** [Sunghah/serialportron#1]
Do you think this is an effective way to communicate commands to an Arduino based project? I am endeavoring to build an app just like this but for an RFID reader. I was envisioning using a drop down to select the port. At which time the user can interact with the reader and tags through the UI. I would love to hear your thoughts. 

Cheers and thanks a bunch for your work.

**Comment by sungpro** [comment]
Hi callen5914,
Thanks for your comments.
I think this is one of many effective ways to communicate with Arduino-based projects "using GUI".
So that the end user doesn't have to do a whole lot and can simply type commands.
Yes, I think a dropdown would display available ports more elegantly. I didn't think of that.
